config/routes.rb
Rails.application.routes.draw do

  get 'users/login', to: 'users#login'
  post 'users/get-session', to: 'users#get_session'
  get 'users/logout'
  get 'users/purchase', to: 'users#purchase', as: 'users_purchase'
  post 'users/conversion', to: 'users#conversion', defaults: { format: 'js' }
  get 'users/checkout', to: 'users#checkout'
  post 'users/checkout', to: 'users#checkout', as: 'users_checkout_post'
  post 'users/payment', to: 'users#payment', defaults: { format: 'js' }
  post 'users/add_friend', to: 'users#add_friend', defaults: { format: 'js' }
  delete 'users/delete_friend', to: 'users#delete_friend', defaults: { format: 'js' }
  post 'users/approve_request', to: 'users#approve_request', defaults: { format: 'js' }
  delete 'users/reject_request', to: 'users#reject_request', defaults: { format: 'js' }
  post 'users/approve_invite', to: 'users#approve_invite', defaults: { format: 'js' }
  delete 'users/reject_invite', to: 'users#reject_invite', defaults: { format: 'js' }
  post 'users/send_invite', to: 'users#send_invite', defaults: { format: 'js'}
  get 'users/forgot-password', to: 'users#forgot_password', as: 'forgot_password'
  post 'users/send-reset-email', to: 'users#send_reset_email', as: 'send_reset_email' # sends reset email
  get 'users/reset-password', to: 'users#reset_password', as: 'reset_password'
  post 'users/update-password', to: 'users#update_password', as: 'update_password' # resets password
  get 'users/purchase_plus_user_view', to: 'users#purchase_plus_user_view'
  post 'users/purchase_plus_user', to: 'users#purchase_plus_user'
  resources :users

  post 'worlds/join_world', to: 'worlds#join_world'
  post 'worlds/leave_world', to: 'worlds#leave_world'
  get 'worlds/invite', to: 'worlds#invite', as: 'world_invite'
  get 'worlds/confirm', to: 'worlds#confirm', as: 'confirm_world'
  resources :worlds
  root to: redirect('/worlds')
  mount GoodJob::Engine => 'good_job' if ENV['RAILS_ENV'] != 'production'

  post 'worlds/game/cell_quest', to: 'users_worlds#cell_quest', as: 'cell_quest'
  post 'worlds/game/gamble', to: 'users_worlds#gamble', as: 'gamble', defaults: { format: 'js' }
  post 'users_worlds/shop', to: 'users_worlds#shop', as: 'shop', defaults: { format: 'js' }
  post 'worlds/game/purchase_item', to: 'users_worlds#purchase_item', as: 'purchase_item', defaults: { format: 'js' }
  post 'users_worlds/inventory', to: 'users_worlds#inventory', as: 'inventory', defaults: { format: 'js' }
  post 'users_worlds/use_item', to: 'users_worlds#use_item', as: 'use_item'
  post '/worlds/game/move', to: 'users_worlds#move_user', as: 'move_user'

  get '/messages/get/:id', to: 'messages#get_all_messages', as: 'get_messages'
  post '/messages/send', to: 'messages#send_message', as: 'send_message'

  post 'quests/quest', to: 'quests#quest', as: 'show_quest', defaults: { format: 'js' }
  resources :quests do
    member do
      post 'complete'
      post 'complete_trivia'
    end
    collection do
      post 'generate'
    end
  end
  post 'blackjack/update_user_credits', to: 'blackjack#update_user_credits', as: 'update_user_credits', defaults: { format: 'js' }
  post 'blackjack/buy_in', to: 'blackjack#buy_in', as: 'buy_in', defaults: { format: 'js' }

end

app/models/world.rb
# frozen_string_literal: true

# The world that a user can join, including functions to initialize and
# update/retrieve information from a displayed grid.
# represents the model class for the worlds object
class World < ApplicationRecord
  has_many :gridsquares, dependent: :destroy

  has_many :user_worlds, dependent: :destroy
  has_many :users, through: :user_worlds

  belongs_to :user

  validates :current_players, numericality: { greater_than_or_equal_to: 0 }
  before_create :init_current_players
  @@dim = 6 # rubocop:disable Style/ClassVars

  # this must be done this way, active storage DOES NOT WORK
  # with after_create call back when seeding!!!!!!!
  def init_if_not_inited
    return unless gridsquares.empty?

    initialize_grid
  end

  def self.dim
    @@dim
  end

  def generate_quest_for(user)
    user_world = user.user_worlds.find_by(world: self)
    return unless user_world

    return if user_world.quests.where(completed: false).exists?

    if Kernel.rand < 0.5
      Quest.generate_movement_for(user_world)
      Rails.logger.debug 'movement quest'
    else
      Quest.generate_trivia_for(user_world)
      Rails.logger.debug 'trivia quest'
    end
  end

  private

  def initialize_grid
    (1..@@dim).each do |row|
      (1..@@dim).each do |col|
        gridsquares.create!(row: row, col: col, buy_in_amount: rand(1..100))
        OpenaiEvent.new(row: row, col: col, world_id: id).save!
      end
    end
  end

  def init_current_players
    self.current_players ||= 0
  end
end

app/controllers/worlds_controller.rb
# frozen_string_literal: true

# WorldController performs basic operations for world generation and state storage.
# rubocop:disable all
class WorldsController < ApplicationController
  before_action :authenticate_user
  before_action :index, only: [:index, :invite]

  def authenticate_user
    @cur_user = User.find_user_by_session_token(cookies[:session])
    return if @cur_user

    flash[:alert] = 'Please login'
    return redirect_to users_login_path
  end

  def world_params
    params.permit(:world_code, :world_name, :is_public, :max_player)
  end

  def get_url(world_id)
    cookies[:previous_url] = request.path
    cookies[:world_id] = world_id
  end

  def show
    # TODO: if private world, check user access
    id = params[:id] # retrieve world ID from URI route
    @world = World.find(id)
    @world.init_if_not_inited
    @data = {}
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)
    @pos_row = @user_world.user_row
    @pos_col = @user_world.user_col
    grid_arr = @world.gridsquares.to_a
    allowed = UserWorld.find_known_squares(@cur_user.id, @world.id)
    grid_arr.each do |cell|
      @data[cell.row] ||= {}
      
      @data[cell.row][cell.col] = allowed.include?([cell.row.to_s, cell.col.to_s]) ? cell : :none
    end
  end

  def index
    flash.discard
    @public_worlds = World.where(is_public: true)
    @private_worlds = World.joins(:user_worlds)
                           .where(is_public: false, user_worlds: { user: @cur_user, request: false })
    @shareable_worlds = World.joins(:user_worlds)
                           .where(is_public: false, user_id: @cur_user.id, user_worlds: { user: @cur_user, request: false })
    @friends = User.where(id: Friendship.friend_ids(@cur_user))
    @requested_friends = User.where(id: Friendship.requested_friend_ids(@cur_user))
    @world_invites = UserWorld.where( user: @cur_user, request: true )
  end

  def invite
    @friend = User.find_by_id(params[:friend_id])
  end

  def new
    @cur_user = User.find_user_by_session_token(cookies[:session])
    # default: render 'new' template
  end

  def create
    new_params = build_world_params

    if invalid_world_params?(new_params)
      flash[:notice] =
        'You have exceeded the worlds player limit. If you would like to upgrade from 5 to 20 purchase plus user.'
      redirect_to new_world_path
    else
      @world = World.create!(new_params)
      UserWorld.create(user: @cur_user, world: @world)
      flash[:notice] = 'World was successfully created.'
      redirect_to worlds_path
    end
  end

  def edit; end

  def update; end

  def destroy
    user_world = UserWorld.find_by(user_id: @cur_user.id, world_id: params[:id])
    world = World.find_by(id: params[:id])

    UserWorld.where(world_id: world.id).destroy_all
    Gridsquare.where(world_id: world.id).destroy_all
    Message.where(world_id: world.id).destroy_all
    OpenaiEvent.where(world_id: world.id).destroy_all

    if World.delete(world)
      @message = 'World deleted.'
    else
      @message = 'Error deleting world.'
    end
    redirect_to worlds_path
  end

  def join_world
    @selected_world = World.find(params[:id].split('_')[1])
    UserWorld.find_or_create_by(user: @cur_user, world: @selected_world)

    if @selected_world.current_players >= @selected_world.max_player.to_i
      flash[:notice] = 'World is full. Please join another world.'
      redirect_to worlds_path
    else
      get_url(@selected_world.id)
      unless params[:is_from_world]
        @selected_world.update(current_players: @selected_world.current_players + 1)
      end

      redirect_to world_path(@selected_world)
    end
  end

  def leave_world
    cookies.delete(:previous_url)
    cookies.delete(:world_id)
    @selected_world = World.find(params[:id])
    UserWorld.find_by(user: @cur_user, world: @selected_world)

    if @selected_world.current_players.positive?
      @selected_world.update(current_players: @selected_world.current_players - 1)
    end

    redirect_to worlds_path
  end

  private

  def build_world_params
    new_params = world_params
    new_params[:user_id] = @cur_user.id
    new_params[:current_players] = 0 # Ensure current_players is set to 0
    new_params
  end

  def invalid_world_params?(params)
    max_players_limit = @cur_user.plus_user? ? 20 : 5
    params[:is_public] == '0' && params[:max_player].to_i > max_players_limit ||
      params[:world_code].blank? || params[:world_name].blank? || params[:max_player].blank?
  end
end

app/views/worlds/index.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title></title>
</head>
<body>
<div class="profile_toolbar">
  <div class="left-stack">
    <%= button_to 'Logout', users_logout_path, method: :get, id: "logout_button", class:"secondary_button"%>
  </div>
  <div class="center-stack">
    <h1 style="font-size: 35px; margin: 15px 0 0;">Welcome, <%= @cur_user.display_name %></h1>
    <div id="flash_partial"></div>
    <div id="flash">
      <% if flash[:notice] %>
        <div class="alert world-creation-alert-box">
          <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
            <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
          </svg></div>
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert world-creation-alert-box">
          <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
            <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
          </svg></div>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="right-stack">
    <div class="box-numeric">
      <%= if @cur_user.available_credits == nil
            0 else @cur_user.available_credits end %>
      <div class="left-stack" style="text-align: center; margin: auto">
        <%= button_to '+', users_purchase_path, method: :get, id: "purchase_button", class: "purchase-button"%>
      </div>
    </div>
  </div>

</div>

<div class="tab">
  <button class="small_button tab_active" onclick="openTab(event, 'public_worlds')">Public Worlds</button>
  <button class="small_button tab_button" onclick="openTab(event, 'private_worlds')">Private Worlds</button>
  <button class="small_button tab_button" onclick="openTab(event, 'friend_list')">Friends</button>
  <button class="small_button tab_button" onclick="openTab(event, 'friend_requests')">Friend Requests</button>
  <button class="small_button tab_button" onclick="openTab(event, 'world_invites')">World Invites</button>
</div>

<div id="public_worlds" class="tab_content active">
  <div style="display: flex; flex-direction: column; align-items: center;">
    <% @public_worlds.each do |world| %>
      <div class="item_box world <%= world.world_name.split.join '_'%>" id= "<%= world.world_name.split.join '_'%>">
        <div class="world-left">
        </div>
        <div class="world-center">
          <h3><%= world.world_name %></h3>
          <p>Max Players: <%= world.max_player %></p>
          <%= button_to "Join", {controller: "worlds", action: "join_world", id: "world_#{world[:id]}", is_from_world: false}, class: "button" %>
        </div>
        <div class="world-right">
          <% if world.user.display_name == @cur_user.display_name %>
            <%= button_to 'Delete', world_path(id: world.id), method: :delete, class: "button", onclick: "flashFadeOut()" %>
          <% else %>
            <h3>Owned by <%=world.user.display_name %> </h3>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="scroll-independent-div-br">
    <%= button_to '+', new_world_path, method: :get, id: "create_button", class: "big-circle-button"%>
  </div>
</div>

<div id="private_worlds" class="tab_content">
  <div style="display: flex; flex-direction: column; align-items: center;" id="private_world_display">
    <% @private_worlds.each do |world| %>
      <div class="item_box world" id= "<%= world.world_name.split.join '_'%>">
        <div class="world-left">
        </div>
        <div class="world-center">
          <h3><%= world.world_name %></h3>
          <p>Max Players: <%= world.max_player %></p>
          <%= button_to "Join", {controller: "worlds", action: "join_world", id: "world_#{world[:id]}", is_from_world: false}, class: "button" %>
        </div>
        <div class="world-right">
          <% if world.user.display_name == @cur_user.display_name %>
            <%= button_to 'Delete', world_path(id: world.id), method: :delete, class: "button", onclick: "flashFadeOut()" %>
          <% else %>
            <h3>Owned by <%=world.user.display_name %> </h3>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="scroll-independent-div-br">
    <%= button_to '+', new_world_path, method: :get, id: "create_button", class: "big-circle-button"%>
  </div>
</div>

<div id="friend_list" class="tab_content">
  <div style="display: flex; flex-direction: column; align-items: center;" id="friend_list_display">
    <div class="world_box">
      <p id="no_friends">Sorry, you currently have no friends. Add some below!</p>
      <button class="button" id="add_friend_button" onclick="addFriend()">Add Friend</button>

      <div id="add_friend_container" style="display: none;">
        <p>Enter your friend's username:</p>
        <%= form_tag "/users/add_friend", :remote => true do %>
          <%= text_field_tag :friend_name, nil, id: 'friend_name', style: "height:30px", class: "textbox"%>
          <%= submit_tag 'Submit', id: 'submit_friend_button', class: "button", onClick: "submitFriend()" %>
        <% end %>
      </div>
    </div>
    <% @friends.each do |friend| %>
      <div class="item_box friend" id="friend_id_<%= friend.id %>">
        <div class="friend_left">
          <%= button_to 'Remove Friend', users_delete_friend_path(friend_id: friend.id), method: :delete, :remote => true, :class => "button", onclick: "flashFadeOut()", style: "margin-top: 10px" %>
        </div>
        <div class="friend_center">
          <h3><%= friend.display_name %></h3>
        </div>
        <div class="friend_right">
          <%= link_to 'Invite to World', world_invite_path(friend_id: friend.id), class: 'button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="friend_requests" class="tab_content">
  <div style="display: flex; flex-direction: column; align-items: center;" id="friend_request_list_display">
    <div id="no_requests" class="info_box">
      <p>You do not have any requests at the moment.</p>
    </div>
    <% @requested_friends.each do |friend| %>
      <div class="item_box friend" id="request_id_<%= friend.id %>">
        <div class="friend_left">
          <%= button_to 'Approve', users_approve_request_path(friend_id: friend.id), method: :post, remote: true, class: "accept_button", onclick: "flashFadeOut()", style: "margin-top: 5px" %>
          <%= button_to 'Reject', users_reject_request_path(friend_id: friend.id), method: :delete, remote: true, class: "not_accept_button", onclick: "flashFadeOut()", style: "margin-top: 5px; margin-left: 10px" %>
        </div>
        <div class="friend_center">
          <h3><%= friend.display_name %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="world_invites" class="tab_content">
  <div style="display: flex; flex-direction: column; align-items: center;" id="world_invite_list_display">
    <div id="no_invites" class="info_box">
      <p>You do not have any world invites at the moment.</p>
    </div>
    <% @world_invites.each do |invite| %>
      <div class="item_box friend" id="invite_id_<%= invite.id %>">
        <div class="friend_left">
          <%= button_to 'Approve', users_approve_invite_path(user_id: invite.user_id, world_id: invite.world_id), method: :post, remote:  true, class: "accept_button", onclick: "flashFadeOut()" %>
          <%= button_to 'Reject', users_reject_invite_path(user_id: invite.user_id, world_id: invite.world_id), method: :delete, remote: true, class: "not_accept_button", style: "margin-left: 10px", onclick: "flashFadeOut()" %>
        </div>
        <div class="friend_center">
          <h3><%= invite.world.world_name %></h3>
        </div>
        <div class="friend_right">
          <h3><%= "Sent by " + invite.world.user.display_name %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!--These are all used to dynamically update the view, as there are actions done on the page that alter it.-->
<script>
    function openTab(evt, tabName) {
        let i, tab_content, tab_links;
        tab_content = document.getElementsByClassName("tab_content");
        for (i = 0; i < tab_content.length; i++) {
            tab_content[i].classList.remove("active");
        }
        tab_links = document.getElementsByClassName("tab_links");
        for (i = 0; i < tab_links.length; i++) {
            tab_links[i].classList.remove("active");
        }
        let active_buttons = document.getElementsByClassName("tab_active")
        console.log(active_buttons.length)
        for (i = 0; i < active_buttons.length; i++) {
            active_buttons[i].classList.add("tab_button")
            active_buttons[i].classList.remove("tab_active")
        }

        document.getElementById(tabName).classList.add("active");
        evt.currentTarget.classList.add("tab_active");
        evt.currentTarget.classList.remove("tab_button")
    }
</script>

<script>
  function flashFadeOut() {
      $('#flash_partial').show();
      setTimeout(function(){
          $('#flash_partial').fadeOut();
      }, 2000);
  }
</script>

<script>
  function addFriend() {
      document.getElementById('add_friend_button').style.display = 'none';
      document.getElementById('add_friend_container').style.display = 'block';
      document.getElementById('friend_name').value = '';
  }

  $(document).ready(function(){
      setTimeout(function(){
          $('#flash').fadeOut();
      }, 2000);
  })
</script>

<script>
    function submitFriend() {
        document.getElementById('add_friend_container').style.display = 'none';
        document.getElementById('add_friend_button').style.display = 'inline-block';

        $('#flash_partial').show();
        setTimeout(function(){
            $('#flash_partial').fadeOut();
        }, 2000);
    }
</script>

<script id="no_friend_message">
    window.noFriendMessage = function() {
      var friends = document.querySelectorAll('[id^="friend_id_"]');
      var friendsLength = friends.length;

      if (friendsLength > 0) {
          document.getElementById('no_friends').style.display = 'none'
      }
      else {
          document.getElementById('no_friends').style.display = 'block'
      }
  }

    window.noFriendMessage();
</script>

<script id="no_request_message">
    window.noRequestMessage = function() {
        var requests = document.querySelectorAll('[id^="request_id_"]');
        var requestLength = requests.length;

        if (requestLength > 0) {
          document.getElementById('no_requests').style.display = 'none'
      } else {
          document.getElementById('no_requests').style.display = 'block'
      }
  }

    window.noRequestMessage();
</script>

<script id="no_invite_message">
    window.noInviteMessage = function() {
        var invites = document.querySelectorAll('[id^="invite_id_"]');
        var inviteLength = invites.length;

        if (inviteLength > 0) {
            document.getElementById('no_invites').style.display = 'none'
        } else {
            document.getElementById('no_invites').style.display = 'block'
        }
    }

    window.noInviteMessage();
</script>

<script id="append_friend_box">
    function appendFriendBox(friend) {
        $('#friend_list_display').append(`
          <div class="item_box friend" id="friend_id_${friend.id}">
            <div class="friend_left">
              ${'<%= j button_to "Remove Friend", users_delete_friend_path(friend_id: "__REPLACE_ID__"), method: :delete, remote: true, class: "button" %>'.replace('__REPLACE_ID__', friend.id)}
            </div>
            <div class="friend_center">
              <h3>${friend.display_name}</h3>
            </div>
            <div class="friend_right">
              ${'<%= j link_to "Invite to World", world_invite_path(friend_id: "__REPLACE_ID__"), class: "button" %>'.replace('__REPLACE_ID__', friend.id)}
            </div>
        </div>
      `);
    }
</script>

<script id="append_world_box">
  function appendWorldBox(world, user) {
      $('#private_world_display').append(`
        <div class="item_box world" id="world_id_${world.world_name.split(' ').join('_')}">
          <div class="world-left">
          </div>
          <div class="world-center">
            <h3>${world.world_name}</h3>
            <p>Code: ${world.world_code}</p>
            <p>Max Players: ${world.max_player}</p>
            ${'<%= j button_to "Join", {controller: "worlds", action: "join_world", id: "__REPLACE_ID__"}, class: "button" %>'.replace('__REPLACE_ID__', "world_" + world.id)}
          </div>
          <div class="world-right">
            <h3>Owned by ${user.display_name}</h3>
          </div>
        </div>
      `);
  }
</script>

</body>
</html>

app/views/worlds/invite.html.erb
<!DOCTYPE html>
<html lang="en-US">
<body>

<div class="profile_toolbar">
  <div class="left-stack">
    <%= button_to '<', worlds_path, method: :get, id: "return_button", class: "big-circle-button"%>
  </div>
  <div class="center-stack">
    <h1 style="font-size: 35px; margin: 15px 0 0;">Sending an world invitation to <%= @friend.display_name%></h1>
    <div id="flash_partial"></div>
    <div id="flash">
      <% if flash[:notice] %>
        <div class="alert world-creation-alert-box">
          <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
            <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
          </svg></div>
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert world-creation-alert-box">
          <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
            <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
          </svg></div>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div style="display: flex; flex-direction: column; align-items: center;">
  <% @shareable_worlds.each do |world| %>
    <div class="item_box world <%= world.world_name.split.join '_'%>">
      <div class="world-left">
      </div>
      <div class="world-center">
        <h3><%= world.world_name %></h3>
        <p>Code: <%= world.world_code %></p>
        <p>Max Players: <%= world.max_player %></p>
        <%= button_to 'Invite to world', users_send_invite_path(friend_id: @friend.id, world_id: world.id), method: :post, :remote => true, :class => "button", onclick: "flashFadeOut()" %>
      </div>
      <div class="world-right">
      </div>
    </div>
  <% end %>
</div>

<script>
    $(document).ready(function(){
        setTimeout(function(){
            $('#flash').fadeOut();
        }, 2000);
    })
</script>

<script>
    function flashFadeOut() {
        $('#flash_partial').show();
        setTimeout(function(){
            $('#flash_partial').fadeOut();
        }, 2000);
    }
</script>
</body>
</html>