config/routes.rb
Rails.application.routes.draw do

  get 'users/login', to: 'users#login'
  post 'users/get-session', to: 'users#get_session'
  get 'users/logout'
  get 'users/purchase', to: 'users#purchase', as: 'users_purchase'
  post 'users/conversion', to: 'users#conversion', defaults: { format: 'js' }
  get 'users/checkout', to: 'users#checkout'
  post 'users/checkout', to: 'users#checkout', as: 'users_checkout_post'
  post 'users/payment', to: 'users#payment', defaults: { format: 'js' }
  post 'users/add_friend', to: 'users#add_friend', defaults: { format: 'js' }
  delete 'users/delete_friend', to: 'users#delete_friend', defaults: { format: 'js' }
  post 'users/approve_request', to: 'users#approve_request', defaults: { format: 'js' }
  delete 'users/reject_request', to: 'users#reject_request', defaults: { format: 'js' }
  post 'users/approve_invite', to: 'users#approve_invite', defaults: { format: 'js' }
  delete 'users/reject_invite', to: 'users#reject_invite', defaults: { format: 'js' }
  post 'users/send_invite', to: 'users#send_invite', defaults: { format: 'js'}
  get 'users/forgot-password', to: 'users#forgot_password', as: 'forgot_password'
  post 'users/send-reset-email', to: 'users#send_reset_email', as: 'send_reset_email' # sends reset email
  get 'users/reset-password', to: 'users#reset_password', as: 'reset_password'
  post 'users/update-password', to: 'users#update_password', as: 'update_password' # resets password
  get 'users/purchase_plus_user_view', to: 'users#purchase_plus_user_view'
  post 'users/purchase_plus_user', to: 'users#purchase_plus_user'
  resources :users

  post 'worlds/join_world', to: 'worlds#join_world'
  post 'worlds/leave_world', to: 'worlds#leave_world'
  get 'worlds/invite', to: 'worlds#invite', as: 'world_invite'
  get 'worlds/confirm', to: 'worlds#confirm', as: 'confirm_world'
  resources :worlds
  root to: redirect('/worlds')
  mount GoodJob::Engine => 'good_job' if ENV['RAILS_ENV'] != 'production'

  post 'worlds/game/cell_quest', to: 'users_worlds#cell_quest', as: 'cell_quest'
  post 'worlds/game/gamble', to: 'users_worlds#gamble', as: 'gamble', defaults: { format: 'js' }
  post 'users_worlds/shop', to: 'users_worlds#shop', as: 'shop', defaults: { format: 'js' }
  post 'worlds/game/purchase_item', to: 'users_worlds#purchase_item', as: 'purchase_item', defaults: { format: 'js' }
  post 'users_worlds/inventory', to: 'users_worlds#inventory', as: 'inventory', defaults: { format: 'js' }
  post 'users_worlds/use_item', to: 'users_worlds#use_item', as: 'use_item'
  post '/worlds/game/move', to: 'users_worlds#move_user', as: 'move_user'

  get '/messages/get/:id', to: 'messages#get_all_messages', as: 'get_messages'
  post '/messages/send', to: 'messages#send_message', as: 'send_message'

  post 'quests/quest', to: 'quests#quest', as: 'show_quest', defaults: { format: 'js' }
  resources :quests do
    member do
      post 'complete'
      post 'complete_trivia'
    end
    collection do
      post 'generate'
    end
  end
  post 'blackjack/update_user_credits', to: 'blackjack#update_user_credits', as: 'update_user_credits', defaults: { format: 'js' }
  post 'blackjack/buy_in', to: 'blackjack#buy_in', as: 'buy_in', defaults: { format: 'js' }

end

app/models/user.rb
# frozen_string_literal: true

require 'bcrypt'

# Model dealing with user accounts
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy, inverse_of: :user
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy,
                                 inverse_of: :user
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :user_worlds, dependent: :destroy
  has_many :worlds, through: :user_worlds

  validates :email, presence: { message: 'is required.' }, 'valid_email_2/email': true
  validates :display_name, presence: { message: 'is required.' }, uniqueness: { message: '%<value>s is taken' }
  has_secure_password
  validate :password_complexity

  def update_session_token
    self.session_token = SecureRandom.hex(32)
    save
  end

  def plus_user?
    plus_user
  end

  def purchase_plus_user
    cost_in_shards = 100 # Define the cost in shards for plus_user access
    if available_credits >= cost_in_shards
      self.available_credits -= cost_in_shards
      self.plus_user = true
      save
      true
    else
      false
    end
  end

  def generate_reset_password_token
    self.reset_password_token = SecureRandom.hex(32)
    self.reset_password_sent_at = Time.now.utc
    save
  end

  def invalid_reset_password_token?
    reset_password_sent_at.nil? || reset_password_token.nil? || reset_password_sent_at < 1.hour.ago
  end

  def update_password(new_password)
    self.password = new_password
    save
  end

  def charge_credits(num)
    return false unless available_credits >= num

    self.available_credits -= num
    save
  end

  private

  # rubocop:disable all 
  # rubo cop complains that it's too long. and too many conditionals. The alternative is to have all
  # these as oneliner functions which is also bad....
  def password_complexity #thanks chatGPT :) 
    return if password.blank?
    password_rules = {
      length: { condition: ->(pwd) { pwd.length >= 12 }, message: 'must be longer than 12 characters' },
      digit: { condition: ->(pwd) { pwd.match?(/\d/) }, message: 'must include a digit' },
      uppercase: { condition: ->(pwd) { pwd.match?(/[A-Z]/) }, message: 'must include one uppercase letter' },
      lowercase: { condition: ->(pwd) { pwd.match?(/[a-z]/) }, message: 'must include one lowercase letter' },
      special_char: { condition: ->(pwd) { pwd.match?(/[\W_]/) }, message: 'must include one special character' }
    }
    password_rules.each do |key, rule|
      unless rule[:condition].call(password)
        errors.add(:password, rule[:message])
        break
      end
    end
  end
  # https://api.rubyonrails.org/v7.1/classes/ActiveModel/SecurePassword/ClassMethods.html
  # use authenticate for checking the password

  def self.find_user_by_display_name(display_name)
    User.where(['display_name = ?', display_name]).first
  end

  def self.find_user_by_session_token(session_token)
    User.where(['session_token = ?', session_token]).first
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller for handling user-related actions.
# rubocop:disable all
class UsersController < ApplicationController
  require 'credit_card_detector'

  def new
    # render default template
  end

  # rubo cop complains that it's too long. But password confirmation checking should not be in the model
  def create
    form = params[:user]
    if form[:password_confirmation] != form[:password]
      flash[:alert] = 'Password confirmation must match'
      return redirect_to new_user_path
    end
    usr = User.new(email: form[:email], display_name: form[:user_name], password: form[:password])
    if usr.valid? && usr.save
      flash[:notice] = 'Account created successfully'
      return redirect_to users_login_path
    end
    flash[:alert] = usr.errors.empty? ? 'Something went wrong' : usr.errors.full_messages.first
    redirect_to new_user_path
  end

  def show; end

  def edit; end

  def update; end

  def login
    cur_user = User.find_user_by_session_token(cookies[:session])
    if cur_user != nil 
      redirect_to worlds_path
    end
  end

  def forgot_password
    # renders the forgot password page
  end

  def send_reset_email
    # send email to user
    user = User.find_by_email(params[:email])
    if user
      user.generate_reset_password_token
      UserMailer.send_reset_password_email(user).deliver_now
      flash[:notice] = 'Password reset email sent!'
      return redirect_to users_login_path
    end
    flash[:alert] = 'User not found from the given email'
    redirect_to forgot_password_path
  end

  def reset_password
    @user = User.find_by_reset_password_token(params[:token])
    if @user.nil? || @user.invalid_reset_password_token?
      flash[:alert] = 'Invalid or expired reset link'
      redirect_to users_login_path
    end
  end

  def update_password
    @user = User.find_by(reset_password_token: params[:token])
    if params[:new_password] != params[:confirm_new_password]
      flash[:alert] = 'Password confirmation must match'
      return redirect_to reset_password_path(token: params[:token])
    end
    if @user.update_password(params[:new_password]) and @user.valid?
      flash[:notice] = 'Password reset successfully'
      return redirect_to users_login_path
    end
    flash[:alert] = @user.errors.empty? ? 'Something went wrong' : @user.errors.full_messages.first
    redirect_to reset_password_path(token: params[:token])
  end

  def get_session
    @user = User.find_user_by_display_name(params[:user_name])
    if @user && @user.authenticate(params[:password]) && @user.update_session_token
      flash[:notice] = 'Login successful'
      cookies[:session] = { value: @user.session_token, expires: 1.week.from_now }
      return redirect_to worlds_path
    end
    flash[:notice] = 'Incorrect username or password'

    redirect_to users_login_path
  end

  def purchase
    @user = User.find_user_by_session_token(cookies[:session])
    if cookies[:previous_url] == nil
      @is_from_game = false
    else
      @is_from_game = true
    end
  end

  def conversion
    shards = params[:shard_input_field]
    currency = params[:currency]

    if shards == ""
      flash[:notice] = 'No amount of shard indicated.'
      redirect_to users_purchase_path
    else
      begin
        raise(ArgumentError) unless shards.match?(/\A\d+\z/)
        flash.clear
        @currency = currency.upcase
        shard_usd_price = 0.75 # default price in USD
        @rate = (ShardsHelper.get_shard_conversion(@currency) * shard_usd_price).round(2)
        @amount = (Integer(shards) * @rate).round(2)
        @num_of_shards = Integer(shards)

        respond_to do |format|
          format.js
        end
      rescue ArgumentError
        flash[:notice] = "Input is not a number. Please try again."
        redirect_to users_purchase_path
      end
    end
  end

  def checkout
    @total_amount = params[:total_amount]
    @with_currency = params[:with_currency]
    @num_of_shards = params[:total_shards]
    @user = User.find_user_by_session_token(cookies[:session])
  end

  def payment
    card_number = params[:card_number]
    expiration_date = params[:expiration_date]
    cvv = params[:cvv]
    billing_address = params[:billing_address]
    num_of_shards = Integer(if params[:total_shards] == "" then 0 else params[:total_shards] end)
    @user = User.find_user_by_session_token(cookies[:session])

    if card_number == "" or expiration_date == "" or cvv == "" or billing_address == ""
      flash[:alert] = "There is an error on processing. Please check your fields are correct."
      redirect_to users_checkout_post_path(total_amount: params[:total_amount], with_currency: params[:with_currency], total_shards: params[:total_shards])
      return
    else
      detector = CreditCardDetector::Detector.new(card_number)
      result = detector.valid_luhn?
      unless result
        flash[:alert] = "Card number is not valid. Please recheck your card number."
        redirect_to users_checkout_post_path(total_amount: params[:total_amount], with_currency: params[:with_currency], total_shards: params[:total_shards])
        return
      end
      unless expiration_date =~ /\A\d\d\d\d\Z/
        flash[:alert] = "Expiration date can only be 4 digits. Please try again."
        redirect_to users_checkout_post_path(total_amount: params[:total_amount], with_currency: params[:with_currency], total_shards: params[:total_shards])
        return
      end
      unless cvv =~ /\A\d\d\d\Z/
        flash[:alert] = "CVV can only be 3 digits. Please try again."
        redirect_to users_checkout_post_path(total_amount: params[:total_amount], with_currency: params[:with_currency], total_shards: params[:total_shards])
        return
      end
      @user.update(available_credits: @user.available_credits + num_of_shards)
      flash[:notice] = "Purchase #{num_of_shards} shards successful! Thank you for your support!"
      redirect_to users_purchase_path
    end
  end

  def logout
    cur_user = User.find_user_by_session_token(cookies[:session])
    flash[:notice] = 'Logout successful'
    cur_user.session_token = nil
    cur_user.save!
    redirect_to users_login_path
  end

  def add_friend
    cur_user = User.find_user_by_session_token(cookies[:session])
    friend_name = params[:friend_name]
    @friend = User.find_by(display_name: friend_name)

    if @friend.nil?
      @message = "User not found."
      respond_to do |format|
        format.js
      end
    elsif @friend == cur_user
      @message = "Unfortunately, you cannot add yourself as a friend."
      respond_to do |format|
        format.js
      end
    else
      existing_friendship = Friendship.find_by(user_id: cur_user.id, friend_id: @friend.id, status: 'accepted')
      inverse_friendship = Friendship.find_by(user_id: @friend.id, friend_id: cur_user.id, status: 'accepted')

      existing_request = Friendship.find_by(user_id: cur_user.id, friend_id: @friend.id, status: 'pending')
      inverse_request = Friendship.find_by(user_id: @friend.id, friend_id: cur_user.id, status: 'pending')

      if existing_friendship || inverse_friendship
        @message = "Friendship already exists!"
        respond_to do |format|
          format.js
        end
      elsif existing_request
        @message = "A request has already been sent!"
        respond_to do |format|
          format.js
        end
      elsif inverse_request
        @message = "This person has sent a request to you already!"
        respond_to do |format|
          format.js
        end
      else
        friendship = Friendship.new(user_id: cur_user.id, friend_id: @friend.id, status: 'pending')

        if friendship.save
          @message = "A friend request has been sent!"
          respond_to do |format|
            format.js
          end
        else
          @message = "Failed to add friendship."
          respond_to do |format|
            format.js
          end
        end
      end
    end
  end

  def delete_friend
    cur_user = User.find_user_by_session_token(cookies[:session])
    @friend = User.find_by(id: params[:friend_id])

    existing_friendship = Friendship.find_by(user_id: cur_user.id, friend_id: params[:friend_id])
    inverse_friendship = Friendship.find_by(user_id: params[:friend_id], friend_id: cur_user.id)

    if existing_friendship
      existing_friendship.destroy
    end
    if inverse_friendship
      inverse_friendship.destroy
    end
    @message = 'Friend removed successfully.'
    respond_to do |format|
      format.js
    end
  end

  def approve_request
    cur_user = User.find_user_by_session_token(cookies[:session])
    @friend = User.find_by(id: params[:friend_id])
    existing_friendship = Friendship.find_by(user_id: cur_user.id, friend_id: params[:friend_id])
    inverse_friendship = Friendship.find_by(user_id: params[:friend_id], friend_id: cur_user.id)

    friendship = existing_friendship || inverse_friendship
    if friendship&.update(status: 'accepted')
      @message = 'Friend accepted!'
    else
      @message = 'Friendship not found!'
    end

    respond_to do |format|
      format.js
    end
  end

  def reject_request
    cur_user = User.find_user_by_session_token(cookies[:session])
    @friend = User.find_by(id: params[:friend_id])

    existing_friendship = Friendship.find_by(user_id: cur_user.id, friend_id: params[:friend_id])
    inverse_friendship = Friendship.find_by(user_id: params[:friend_id], friend_id: cur_user.id)

    if existing_friendship
      existing_friendship.destroy
    end
    if inverse_friendship
      inverse_friendship.destroy
    end
    @message = 'Friend request declined.'
    respond_to do |format|
      format.js
    end
  end

  def send_invite
    @friend = User.find_by(id: params[:friend_id])
    @world = World.find_by(id: params[:world_id])

    existing_world = UserWorld.find_by(user_id: @friend.id, world_id: @world.id, request: false)

app/views/users/_conversion.html.erb
<div class="purchase-box" id="conversion-box">
  <label for="shard_input" style="font-size: 30px">Conversion Rate</label>
  <label>Price per shard: <%= rate %> <%= currency %>/shard</label>
  <label>Total amount: <%= amount %> <%= currency %></text></label>
  <%= form_tag "/users/checkout", method: :post, id: 'checkout_button_form' do %>
    <input type="hidden" name="total_amount" id="total_amount" value="<%= amount %>"/>
    <input type="hidden" name="with_currency" id="with_currency" value="<%= currency %>"/>
    <input type="hidden" name="total_shards" id="total_shards" value="<%= num_of_shards %>"/>
    <%= submit_tag 'Proceed to Checkout', method: :post, id: 'checkout_button', class: "highlight_button", data: { disable_with: false }%>
  <% end %>
</div>

app/views/users/_flash_partial.html.erb
<div class="alert shard-alert-box">
  <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
    <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
  </svg></div>
  <%= message %>
</div>

app/views/users/add_friend.js.erb
$('#flash_partial').html("<%= escape_javascript(render :partial => 'flash_partial', :locals => {:message => @message}) %>");

app/views/users/approve_invite.js.erb
$('#flash_partial').html("<%= escape_javascript(render :partial => 'flash_partial', :locals => {:message => @message}) %>");

$("#invite_id_<%= @invite.id %>").remove();

window.appendWorldBox(<%= @world.to_json.html_safe %>, <%= @user.to_json.html_safe %>);
window.noInviteMessage();

app/views/users/approve_request.js.erb
$('#flash_partial').html("<%= escape_javascript(render :partial => 'flash_partial', :locals => {:message => @message}) %>");

$("#request_id_<%= @friend.id %>").remove();

window.appendFriendBox(<%= @world.to_json.html_safe %>);
window.noFriendMessage();
window.noRequestMessage();

app/views/users/checkout.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>Worlds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="profile_toolbar">
    <div class="scroll-independent-div-tl">
      <%= button_to '<', users_purchase_path, method: :get, id: "return_button", class: "big-circle-button"%>
    </div>

    <div class="center-stack">
      <h1 style="font-size: 35px; margin: 15px 0 0;">Checkout</h1>
      <div id="flash_partial" style="z-index: 10"></div>
      <div id="flash">
        <% if flash[:alert] %>
          <div class="alert world-creation-alert-box">
            <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
              <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
            </svg></div>
            <%= flash[:alert] %></div>
        <% end %>
      </div>
    </div>
    <div class="right-stack">
      <div class="box-numeric">
        <%= if @user.available_credits == nil
              0 else @user.available_credits end %>
      </div>
    </div>
  </div>

  <div class="lower-div-after-nav">
    <div class="purchase-box">
      <%= form_tag "/users/payment", id: 'payment_form' do %>
        <div>
          <label for="card_number_field">Card Number:</label>
          <%= text_field_tag :card_number, nil, id: 'card_number_field', class: "textbox", :maxlength => 16 %>
        </div>
        <div>
          <label for="expiration_date_field">Expiration Date (MMYY):</label>
          <%= text_field_tag :expiration_date, nil, id: 'expiration_date_field', class: "textbox", :maxlength => 4 %>
        </div>
        <div>
          <label for="cvv_field">CVV:</label>
          <%= text_field_tag :cvv, nil, id: 'cvv_field', class: "textbox", :maxlength => 3 %>
        </div>
        <div>
          <label for="billing_address_field">Billing Address:</label>
          <%= text_field_tag :billing_address, nil, id: 'billing_address_field', class: "textbox"%>
        </div>
        <label for="shard_receive" style="font-size: 30px">Receive: <%= @num_of_shards %> shards</label>
        <label for="total_amount" style="font-size: 30px">Total: <%= @total_amount %> <%= @with_currency %></label>
        <input type="hidden" name="total_shards" id="total_shards" value="<%= @num_of_shards %>"/>
        <input type="hidden" name="total_amount" id="total_amount" value="<%= @total_amount %>"/>
        <input type="hidden" name="with_currency" id="with_currency" value="<%= @with_currency %>"/>
        <%= submit_tag 'Pay', id: 'pay_button', class: "highlight_button", onclick: "handle_pay()" %>
      <% end %>
    </div>
  </div>

  <script>
      $(document).ready(function(){
          setTimeout(function(){
              $('#flash').fadeOut();
          }, 2000);
      })

      function handle_pay() {
          $('#flash_partial').show();
          setTimeout(function(){
              $('#flash_partial').fadeOut();
          }, 2000);
      }
  </script>
</body>



app/views/users/purchase.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>Worlds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="profile_toolbar">
    <div class="scroll-independent-div-tl">
      <% if @is_from_game == true %>
        <%= button_to '<', cookies[:previous_url], params: {id: "world_#{cookies[:world_id]}", is_from_world: true}, method: :post, id: "return_button", class: "big-circle-button"%>
      <% else %>
        <%= button_to '<', worlds_path, method: :get, id: "return_button", class: "big-circle-button"%>
      <% end %>
    </div>

    <div class="center-stack">
      <h1 style="font-size: 35px; margin: 20px 10px 10px;">Shop</h1>

    </div>
    <div class="right-stack">
      <div class="box-numeric">
        <%= if @user.available_credits == nil
              0 else @user.available_credits end %>
      </div>
      <% if @is_from_game == false %>
        <%= button_to 'Purchase Plus User', users_purchase_plus_user_view_path, method: :get, id: "purchase_plus_user_button", class: "secondary_button"%>
      <% end %>
    </div>
  </div>

  <div class="lower-div-after-nav">
    <% if flash[:notice] %>
      <div id="flash" class="alert shard-alert-box">
        <div class="alert_icon"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30">
          <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z"></path>
        </svg></div>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="purchase-box">
      <%= form_tag "/users/conversion", id: 'world_add_form', remote: true do %>
        <div>
          <label for="shard_input_field" style="font-size: 30px">Enter the amount of shards:</label>
            <div style="display: flex; width: 100%">
              <%= text_field_tag :shard_input_field, nil, id: 'shard_input_field', class: "textbox-center-large-size"%>
              <input type="hidden" name="currency" id="currency-hidden" value="usd"/>
              <div class="dropdown">
                <button class="highlight_button" id="currency" disabled>
                  USD
                </button>
                <div class="dropdown-content" id="dropdown-content">
                  <button id="usd" class="drop-button" onclick="change_currency(event, 'usd')">USD</button>
                  <button id="cad" class="drop-button" onclick="change_currency(event, 'cad')">CAD</button>
                  <button id="gbp" class="drop-button" onclick="change_currency(event, 'gbp')">GBP</button>
                  <button id="eur" class="drop-button" onclick="change_currency(event, 'eur')">EUR</button>
                  <button id="jpy" class="drop-button" onclick="change_currency(event, 'jpy')">JPY</button>
                </div>
              </div>
            </div>
        </div>
        <%= submit_tag 'Convert', id: 'convert_button', class: "highlight_button", disabled: false, data: { disable_with: false } %>
      <% end %>
    </div>
    <div id="conversion">

    </div>
  </div>


  <script>
      function change_currency(event, currency) {
          $("#currency-hidden").val(currency)
          $("#currency").text(currency.toUpperCase())
      }

      $(document).ready(function(){
          setTimeout(function(){
              $('#flash').fadeOut();
          }, 2000);
      })
  </script>
</body>



app/views/users/purchase_plus_user_view.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>Purchase Plus User</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'purchase_plus_user', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="profile_toolbar">
  <div class="scroll-independent-div-tl">
    <%= button_to '<', "purchase", method: :get, id: "return_button", class: "big-circle-button"%>
  </div>

  <div class="center-stack">
    <h1 style="font-size: 35px; margin: 20px 10px 10px;">Shop</h1>
  </div>
  <div class="right-stack">
    <div class="box-numeric">
      <%= if @user.available_credits == nil
            0 else @user.available_credits end %>
    </div>
  </div>
</div>
<div class="lower-div-after-nav">
  <div id="flash_messages">
    <% if flash[:notice] %>
      <div class="alert notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert"><%= flash[:alert] %></div>
    <% end %>
  </div>

  <div class="purchase-plus-box">
    <h1>Purchase Plus User Access</h1>
    <p style="font-size: 20px">Cost: <b>100</b> Shards</p>
    <p style="font-size: 20px">With Plus User Access, you are able to create world with <b>more than 5</b> users be able to join!</p>
    <% if @user.plus_user? %>
      <p style="font-size: 20px">You already have Plus User access</p>
    <% else %>
      <%= form_tag "/users/purchase_plus_user", method: :post do %>
        <button type="submit" class="secondary_button" style="margin-bottom: 5px">Purchase Plus User Access</button>
      <% end %>
    <% end %>
    <%= button_to 'Back to Worlds', worlds_path, method: :get, class: "small_button highlight_button" %>
  </div>
</div>


</body>
</html>