config/routes.rb
Rails.application.routes.draw do

  get 'users/login', to: 'users#login'
  post 'users/get-session', to: 'users#get_session'
  get 'users/logout'
  get 'users/purchase', to: 'users#purchase', as: 'users_purchase'
  post 'users/conversion', to: 'users#conversion', defaults: { format: 'js' }
  get 'users/checkout', to: 'users#checkout'
  post 'users/checkout', to: 'users#checkout', as: 'users_checkout_post'
  post 'users/payment', to: 'users#payment', defaults: { format: 'js' }
  post 'users/add_friend', to: 'users#add_friend', defaults: { format: 'js' }
  delete 'users/delete_friend', to: 'users#delete_friend', defaults: { format: 'js' }
  post 'users/approve_request', to: 'users#approve_request', defaults: { format: 'js' }
  delete 'users/reject_request', to: 'users#reject_request', defaults: { format: 'js' }
  post 'users/approve_invite', to: 'users#approve_invite', defaults: { format: 'js' }
  delete 'users/reject_invite', to: 'users#reject_invite', defaults: { format: 'js' }
  post 'users/send_invite', to: 'users#send_invite', defaults: { format: 'js'}
  get 'users/forgot-password', to: 'users#forgot_password', as: 'forgot_password'
  post 'users/send-reset-email', to: 'users#send_reset_email', as: 'send_reset_email' # sends reset email
  get 'users/reset-password', to: 'users#reset_password', as: 'reset_password'
  post 'users/update-password', to: 'users#update_password', as: 'update_password' # resets password
  get 'users/purchase_plus_user_view', to: 'users#purchase_plus_user_view'
  post 'users/purchase_plus_user', to: 'users#purchase_plus_user'
  resources :users

  post 'worlds/join_world', to: 'worlds#join_world'
  post 'worlds/leave_world', to: 'worlds#leave_world'
  get 'worlds/invite', to: 'worlds#invite', as: 'world_invite'
  get 'worlds/confirm', to: 'worlds#confirm', as: 'confirm_world'
  resources :worlds
  root to: redirect('/worlds')
  mount GoodJob::Engine => 'good_job' if ENV['RAILS_ENV'] != 'production'

  post 'worlds/game/cell_quest', to: 'users_worlds#cell_quest', as: 'cell_quest'
  post 'worlds/game/gamble', to: 'users_worlds#gamble', as: 'gamble', defaults: { format: 'js' }
  post 'users_worlds/shop', to: 'users_worlds#shop', as: 'shop', defaults: { format: 'js' }
  post 'worlds/game/purchase_item', to: 'users_worlds#purchase_item', as: 'purchase_item', defaults: { format: 'js' }
  post 'users_worlds/inventory', to: 'users_worlds#inventory', as: 'inventory', defaults: { format: 'js' }
  post 'users_worlds/use_item', to: 'users_worlds#use_item', as: 'use_item'
  post '/worlds/game/move', to: 'users_worlds#move_user', as: 'move_user'

  get '/messages/get/:id', to: 'messages#get_all_messages', as: 'get_messages'
  post '/messages/send', to: 'messages#send_message', as: 'send_message'

  post 'quests/quest', to: 'quests#quest', as: 'show_quest', defaults: { format: 'js' }
  resources :quests do
    member do
      post 'complete'
      post 'complete_trivia'
    end
    collection do
      post 'generate'
    end
  end
  post 'blackjack/update_user_credits', to: 'blackjack#update_user_credits', as: 'update_user_credits', defaults: { format: 'js' }
  post 'blackjack/buy_in', to: 'blackjack#buy_in', as: 'buy_in', defaults: { format: 'js' }

end

app/controllers/users_worlds_controller.rb
# frozen_string_literal: true

# Controller for handling user-world actions.
class UsersWorldsController < ApplicationController
  before_action :authenticate_user
  require 'json'

  def authenticate_user
    @cur_user = User.find_user_by_session_token(cookies[:session])
    return if @cur_user

    flash[:alert] = 'Please login'
    redirect_to users_login_path
  end

  def cell_quest
    world = params[:world_id]
    @user_world = UserWorld.find_by_ids(@cur_user.id, world)
  end

  # rubocop:disable Metrics/MethodLength
  def move_user
    world = params[:world_id]
    user_world = UserWorld.find_by_ids(@cur_user.id, world)
    row = user_world.user_row
    col = user_world.user_col
    dest_row = params[:dest_row]
    dest_col = params[:dest_col]

    isfree = UserWorld.free_move?(row, col, dest_row, dest_col)

    unless isfree
      if user_world.speed_boost?
        user_world.update_speed_count
      else
        charge_res = @cur_user.charge_credits(0.75)
        unless charge_res
          flash[:alert] = 'Insufficient credits!'
          return render json: { error: 'Insufficient credits!' }, status: :bad_request
        end
      end
    end

    user_world.set_position(dest_row, dest_col)
    Quest.check_and_complete_movement_quest(user_world, dest_row, dest_col, flash)
    render json: { error: 'none' }, status: :ok
  end

  def gamble
    @cur_user = User.find_user_by_session_token(cookies[:session])
    @world = World.find(params[:world_id])
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)
    @gridsquare = Gridsquare.find_by_row_col(@world, @user_world.user_row, @user_world.user_col)

    if @gridsquare.buy_in_amount.nil? || @gridsquare.buy_in_amount % 5 != 0
      @gridsquare.set_random_buy_in_amount
      @gridsquare.save
    end

    respond_to do |format|
      format.js
    end
  end

  def shop
    @cur_user = User.find_user_by_session_token(cookies[:session])
    @world = World.find(params[:world_id])
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)

    @items = Item.all

    respond_to do |format|
      format.js
    end
  end

  def purchase_item
    @cur_user = User.find_user_by_session_token(cookies[:session])
    @world = World.find(params[:world_id])
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)
    @items = []
    list_of_items = JSON.parse(params[:items_id])

    list_of_items.each_key do |item|
      @items.push(Item.where(item_name: item).first) if list_of_items[item] != 0
    end

    @items.each do |item|
      if @cur_user.available_credits < (list_of_items[item.item_name] * item.price)
        flash[:alert] = 'No sufficient shard to purchase'
        break
      end

      @user_item = InventoryItem.find_or_create_by(user_world_id: @user_world.id, item_id: item.id)
      @user_item.increment(:amount_available, list_of_items[item.item_name])
      @user_item.update(item_name: item.item_name)
      @user_item.save
      @cur_user.update(available_credits: @cur_user.available_credits - (list_of_items[item.item_name] * item.price))

      flash[:alert] = if @items.length == 1
                        "Bought #{@items[0].item_name} item."
                      else
                        "Bought #{@items[0].item_name} item and more."
                      end
    end

    redirect_to world_path(params[:world_id])
  end

  def inventory
    @cur_user = User.find_user_by_session_token(cookies[:session])
    @world = World.find(params[:world_id])
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)

    @inventory_items = InventoryItem.where(user_world_id: @user_world&.id).order(item_name: :asc)

    respond_to do |format|
      format.js
    end
  end

  def use_item
    @cur_user = User.find_user_by_session_token(cookies[:session])
    @world = World.find(params[:world_id])
    @user_world = UserWorld.find_by_ids(@cur_user.id, @world.id)

    @user_item = InventoryItem.find_by(id: params[:inventory_item_id])

    item_name = @user_item.consume_item

    flash[:alert] = "#{item_name} was used!"
    redirect_to world_path(params[:world_id])
  end
  # rubocop:enable Metrics/MethodLength
end

app/views/users_worlds/_inventory.html.erb
<div class="floating-partial-box" id="inventory-box">
  <label for="shard_input" style="font-size: 30px; padding-bottom: 10px">Inventory</label>
  <% if items.any? %>
    <% items.each_with_index do |item, index| %>
      <div class="row-container">
        <p class="item-name"><%= item.item_name %></p>
        <p class="item-quantity" style="font-weight: normal" id="amount_text_<%= index %>">Quantity: <%= item.amount_available %></p>
        <%= form_tag use_item_path, method: :post, id: 'use_item_form' do %>
          <input type="hidden" name="world_id" id="world_id" value="<%= @world.id %>"/>
          <input type="hidden" name="inventory_item_id" id="inventory_item_id" value="<%= item.id %>"/>
          <button id="use_item_button" class="accept_button" onclick="enable_background_interaction()">Use</button>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="no-items-message">
      <p>No items in inventory</p>
    </div>
  <% end %>
</div>

app/views/users_worlds/_shop.html.erb
<div class="floating-partial-box" id="cell-shop-box">
  <label for="shard_input" style="font-size: 30px; padding-bottom: 10px">Shop</label>
  <% items.each_with_index do |item, index| %>
    <div class="row-container">
      <p class="item-description"><%= item.item_name %></p>
      <p class="item-price" style="font-weight: normal" id="amount_text_<%= index %>">Price: <%= item.price %> shard</p>
      <button class="plus-minus-button" id="minus_button_<%= index %>" onclick="{updateItemAmount(-1, <%= index %>); buy_items()}" disabled style="background-color: #6a7588; transition: none;">-</button>
      <span class="amount" id="amount_<%= index %>">0</span>
      <button class="plus-minus-button" id="plus_button_<%= index %>" onclick="{updateItemAmount(1, <%= index %>); buy_items()}">+</button>
    </div>
  <% end %>
  <%= form_tag purchase_item_path, method: :post, id: 'buy_form' do %>
    <input type="hidden" name="world_id" id="world_id" value="<%= @world.id %>"/>
    <input type="hidden" name="items_id" id="items_id"/>
    <button id="buy_button" class="accept_button" onclick="enable_background_interaction()" disabled style="background-color: #808391; transition: none;">Buy</button>
  <% end %>

  <script>
      function updateItemAmount(change, index) {
          let currentAmount = parseInt(document.getElementById(`amount_${index}`).textContent, 10);
          currentAmount = Math.max(0, currentAmount + change);


          if (currentAmount === 0) {
              document.getElementById(`minus_button_${index}`).disabled = true
              document.getElementById(`minus_button_${index}`).style.backgroundColor = "#808391"
          } else {
              document.getElementById(`minus_button_${index}`).disabled = false
              document.getElementById(`minus_button_${index}`).style.backgroundColor = "#6fb2cd"
              document.getElementById(`minus_button_${index}`).style.transition = "background-color 0.3s ease, transform 0.2s ease"
          }

          document.getElementById(`amount_${index}`).textContent = currentAmount.toString();
      }
  </script>
  <script>
    function buy_items() {
        let requestDict = {}
        const itemElements = document.getElementsByClassName('item-description');
        const amountElements = document.getElementsByClassName('amount');

        for (let i = 0; i < itemElements.length; i++) {
            console.log(itemElements[i].textContent)
            console.log(amountElements[i].textContent)
            requestDict[itemElements[i].textContent] = parseInt(amountElements[i].textContent);
        }

        for (let i = 0; i < amountElements.length; i++) {
            if (parseInt(amountElements[i].textContent) > 0) {
                document.getElementById("buy_button").disabled = false
                document.getElementById("buy_button").style.backgroundColor = "#2ba62e"
                document.getElementById("buy_button").style.transition = "background-color 0.3s ease, transform 0.2s ease"
                break
            }

            document.getElementById("buy_button").disabled = true
            document.getElementById("buy_button").style.backgroundColor = "#808391"
            document.getElementById("buy_button").style.transition = "none"
        }

        document.getElementById("items_id").value = JSON.stringify(requestDict)
    }
  </script>
</div>

app/views/users_worlds/gamble.js.erb
$('#gamble').html("<%= escape_javascript(render :partial => 'gamble', :locals => {:gridsquare => @gridsquare, :user => @cur_user, :world_id => @world.id }) %>");

app/views/users_worlds/inventory.js.erb
$('#inventory').html("<%= escape_javascript(render :partial => 'inventory', :locals => {:items => @inventory_items }) %>");

app/views/users_worlds/purchase_item.js.erb
$('#flash_partial').html("<%= escape_javascript(render :partial => 'users/flash_partial', :locals => {:message => @message}) %>");

app/views/users_worlds/shop.js.erb
$('#shop').html("<%= escape_javascript(render :partial => 'shop', :locals => {:items => @items }) %>");